// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmzsjiceq-2eNNLWCrYGHkCT5HE8AL1Mc',
    appId: '1:791567469984:web:48c5f65e4a506db6ab28c5',
    messagingSenderId: '791567469984',
    projectId: 'dalel-5819b',
    authDomain: 'dalel-5819b.firebaseapp.com',
    storageBucket: 'dalel-5819b.firebasestorage.app',
    measurementId: 'G-3C8K2XZGQC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTRPG3BmVX0FpuRaAEPU2mMWOQvHwDFVQ',
    appId: '1:791567469984:android:6be5d2bc27b6ecc2ab28c5',
    messagingSenderId: '791567469984',
    projectId: 'dalel-5819b',
    storageBucket: 'dalel-5819b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgP-n48jR8qWG4-TQFk11eYEKKAicaztc',
    appId: '1:791567469984:ios:5b86ad2ce296c7b7ab28c5',
    messagingSenderId: '791567469984',
    projectId: 'dalel-5819b',
    storageBucket: 'dalel-5819b.firebasestorage.app',
    iosBundleId: 'com.example.dalel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgP-n48jR8qWG4-TQFk11eYEKKAicaztc',
    appId: '1:791567469984:ios:5b86ad2ce296c7b7ab28c5',
    messagingSenderId: '791567469984',
    projectId: 'dalel-5819b',
    storageBucket: 'dalel-5819b.firebasestorage.app',
    iosBundleId: 'com.example.dalel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmzsjiceq-2eNNLWCrYGHkCT5HE8AL1Mc',
    appId: '1:791567469984:web:c7ba33e32fd9b2b9ab28c5',
    messagingSenderId: '791567469984',
    projectId: 'dalel-5819b',
    authDomain: 'dalel-5819b.firebaseapp.com',
    storageBucket: 'dalel-5819b.firebasestorage.app',
    measurementId: 'G-RD15ZBXY6F',
  );
}
